# pytest settings optimized for development cycles.
#
# Differences from pytest.ini:
# - Removing `--cov license_manager` makes it possible to scope coverage reports to specific modules.
# - Warnings are ignored.
#
# Example usage:
# ```
# # Test only one domain and report coverage only for that domain:
# pytest -c pytest.local.ini license_manager/apps/core --cov=license_manager.apps.core
# pytest -c pytest.local.ini license_manager/apps/subscriptions --cov=license_manager.apps.subscriptions
#
# # Test only one file or function without generating coverage.
# pytest -c pytest.local.ini license_manager/apps/subscriptions/tests/test_models.py
# ```
[pytest]
DJANGO_SETTINGS_MODULE = license_manager.settings.test
addopts = --cov-report term-missing --cov-report xml -W ignore
norecursedirs = .* docs requirements

# Filter depr warnings coming from packages that we can't control.
filterwarnings =
	ignore:.*urlresolvers is deprecated in favor of.*:DeprecationWarning:auth_backends.views:5
	ignore:.*invalid escape sequence.*:DeprecationWarning:.*(newrelic|uritemplate|psutil).*
	ignore:.*the imp module is deprecated in favour of importlib.*:DeprecationWarning:.*distutils.*
