# Generated by Django 5.2.11 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0078_alter_subscriptionplanrenewal_salesforce_opportunity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='expiration_reminder_sent_date',
            field=models.DateTimeField(blank=True, help_text='Date when the license expiration reminder email was sent to the learner.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='expiration_reminder_sent_date',
            field=models.DateTimeField(blank=True, help_text='Date when the license expiration reminder email was sent to the learner.', null=True),
        ),
    ]
