# Generated by Django 5.2.11 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0079_license_expiration_reminder_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='subscription_plan_expiration_email_sent_date',
            field=models.DateTimeField(blank=True, help_text='Date when the subscription plan expiration email was sent to the learner.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='subscription_plan_expiration_email_sent_date',
            field=models.DateTimeField(blank=True, help_text='Date when the subscription plan expiration email was sent to the learner.', null=True),
        ),
    ]
