# Generated by Django 5.2.11 on 2026-03-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0080_license_subscription_plan_expiration_email_sent_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_netsuite_id',
        ),
    ]
