# Generated by Django 5.2.11 on 2026-06-08 00:00

from django.db import migrations


# Canonical list of all Essentials Academy offerings.
ACADEMY_PRODUCT_NAMES = [
    'SSP Essentials AI Academy',
    'SSP Essentials Sustainability Academy',
    'SSP Essentials Tech and Digital Academy',
    'SSP Essentials Data Academy',
    'SSP Essentials Management Academy',
    'SSP Essentials Leadership Academy',
    'SSP Essentials Supply Chain Academy',
    'SSP Essentials Communication Academy',
]

PLAN_TYPE_LABELS = [
    'self-service-trial',
]


def populate_essentials_academy_products(apps, schema_editor):
    PlanType = apps.get_model('subscriptions', 'PlanType')
    Product = apps.get_model('subscriptions', 'Product')

    plan_types = PlanType.objects.filter(label__in=PLAN_TYPE_LABELS)

    for plan_type in plan_types.iterator():
        for product_name in ACADEMY_PRODUCT_NAMES:
            Product.objects.get_or_create(
                name=product_name,
                plan_type=plan_type,
                defaults={'description': product_name},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0081_remove_unique_netsuite_id'),
    ]

    operations = [
        migrations.RunPython(populate_essentials_academy_products, migrations.RunPython.noop),
    ]
