# Generated by Django 5.2.15 on 2026-08-04 07:37

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0082_add_all_academies_subscription_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseAction",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enterprise_customer_uuid", models.UUIDField(db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("activated", "Activated"),
                            ("revoked", "Revoked"),
                            ("renewed", "Renewed"),
                            ("expired", "Expired"),
                            ("deleted", "Deleted"),
                            ("snapshot_revert", "Snapshot Revert"),
                            ("plan_maintenance", "Plan Maintenance"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("learner", "Learner"),
                            ("system", "System"),
                        ],
                        max_length=32,
                    ),
                ),
                ("actor_lms_user_id", models.IntegerField(blank=True, null=True)),
                ("learner_lms_user_id", models.IntegerField(blank=True, null=True)),
                (
                    "learner_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "learner_external_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin_ui", "Admin UI"),
                            ("admin_api_bulk", "Admin API Bulk"),
                            ("api", "API"),
                            ("celery_task", "Celery Task"),
                            ("renewal_job", "Renewal Job"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "license",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="actions",
                        to="subscriptions.license",
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="license_actions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["license", "created"],
                        name="idx_licaction_license_created",
                    ),
                    models.Index(
                        fields=["enterprise_customer_uuid", "created"],
                        name="idx_licaction_entcust_created",
                    ),
                    models.Index(
                        fields=["subscription_plan", "created"],
                        name="idx_licaction_subplan_created",
                    ),
                ],
            },
        ),
    ]
